Match
(qstnService:Question {uuid: 'c0600456-9a91-49d3-8baa-6067554b4b92'})

CREATE
//Answer

(ansEmerging:Answer {
    uuid: 'a67c7487-5ff5-4818-bba9-d5dee038b09d',
    text: 'Emerging technology products and services',
    hint: 'Access emerging technologies in a wide range of areas. For example:
    <ul>
        <li>Access emerging technologies in a wide range of areas. For example:</li>
        <li>software that helps to reduce manual processes including artificial intelligence and speech recognition software</li>
        <li>technologies to plan, design and build transportation systems</li>
        <li>engineering and materials science services to create new compliant materials </li>
        <li>data management services </li>
        <li>wearable technology such as medical devices</li>
    </ul>'
}),

(ansTransport:Answer {uuid: 'aad772c0-be48-48aa-9aeb-3e7064b262d0', text: 'Transport technology services'}),

(ansIoT:Answer {
    uuid: '75dcac8d-efd7-4a96-a19b-9028001dd132',
    text: 'Internet of Things (IoT)',
    hint: 'Describes physical objects with sensors, processing ability, software or other technologies. The purpose of these objects is to connect and exchange data with other devices and systems over the internet, or other communications networks. Examples can include:
    <ul>
        <li>data management, security and platforms</li>
        <li>network and connectivity equipment</li>
    </ul>'
}),

(ansAI:Answer {
    uuid: 'b426af97-aa09-48ae-ad4c-024ab36fecda',
    text: 'Artificial Intelligence (AI) and automation',
    hint: 'AI involves using computer software to do things that traditionally require human intelligence. Automation is a type of software that follows pre-programmed rules, that can help reduce manual processes'
}),

(ansSimulated:Answer {
    uuid: '7ba6694e-c7e8-4e51-9369-badb6e8217bd',
    text: 'Simulated and enhanced environments',
    hint: 'This refers to the programming environment of a computer that is dedicated to systems simulation and is created to imitate a real-world process over time. Service examples includes: 
    <ul>
        <li>spatial computing: computers blend data from the world around them to perform real actions in a natural way (such as using software to control lights in a room)</li>
        <li>augmented reality: use apps, software and hardware to create an interactive experience by blending reality with digital content</li>§
        <li>virtual reality</li>
    </ul>'
}),

(ansEngineering:Answer {
    uuid: '3e7e9302-f845-44e6-a8f3-a19b2dfff8d1',
    text: 'Engineering and materials science',
    hint: 'This is is the research of properties and structures, such as: 
    <ul>
        <li>metals</li>
        <li>ceramics</li>
        <li>plastics</li>
        <li>composites</li>
        <li>nanomaterials (extremely small substances)</li>
    </ul> In order to create new materials that meet certain mechanical, electrical, and chemical requirements'
}),

(ansData:Answer {
    uuid: '34bfb4e9-8a56-4557-88a0-327f3de03635',
    text: 'Data',
    hint: 'Data technology sector includes solutions for data management, and products or services that are based on data generated by both human and machines'
}),

(ansWearables:Answer {
    uuid: 'c7a401d3-8376-45db-b22e-199493124b8c',
    text: 'Wearables',
    hint: 'Wearable technology is any kind of electronic device designed to be worn on the user\'s body, such as:
    <ul>
        <li>medical devices</li>
        <li>clothing or elements of clothing</li>
        <li>displays</li>
        <li>exoskeleton / muscle computer interface</li>
        <li>sensors</li>
        <li>smart cards</li>
    </ul>'
}),

(ansTransport2:Answer {
    uuid: '3bfd2548-4ddc-4c6b-8a58-bd6f99fee376',
    text: 'Transport',
    hint: 'Transportation technology. New technologies to plan, design, build, and operate transportation systems, improvements and methods'
}),

(ansImplementation:Answer {
    uuid: '31a6653b-b167-4665-9255-9a8b354017d3',
    text: 'Implementation of security controls',
    hint: 'Technology that assists security controls, such as:
    <ul>
        <li>security systems that is designed to prevent access to a building</li>
        <li>body-worn cameras</li>
        <li>environmental monitoring</li>
        <li>cameras and visual detection</li>
    </ul>'
}),

// --

(ansTPS:Answer {
    uuid: '74a5038d-a939-4cd5-bebb-0578dba01919',
    text: 'Transport professional services',
    hint: 'Transport related solutions. Professional services, consultancy or project management ,such as:
    <ul>
        <li>feasibility study services</li>
        <li>inspection service</li>
        <li>transport modeling </li>
    </ul> (a digital replica of a transport system)'
}),

(ansTPC:Answer {
    uuid: 'f32eaad0-5589-4813-a71f-80b5b9b804d4',
    text: 'Transport and Pedestrian Control',
    hint: 'Products, services or systems to support transport and pedestrian controls. Such as:
    <ul>
        <li>controlled pedestrian crossing</li>
        <li>CCTV used in transport surveillance and vehicle monitoring</li>
        <li>signal sensor products</li>
        <li>parking and access control systems</li>
    </ul>'
}),

(ansTSL:Answer {
    uuid: '77099a94-c5ce-41ca-a72a-bf53006de30d',
    text: 'Transport signage and lighting',
    hint: 'Message signs and exterior lighting to support transport and pedestrians for road, rail, aviation and marine, such as:
    <ul>
        <li>lighting control systems</li>
        <li>upgrade of existing assets to high efficiency lighting (such as LED)</li>
        <li>ancillary road equipment such as cabinets and cables (copper and fibre optic)</li>
    </ul>'
}),

(ansTDS:Answer {
    uuid: '23b6bc67-4827-44f9-8861-da81c5b70329',
    text: 'Transport Data Services',
    hint: 'Self monitoring analysis and reporting technologies (SMART), data management and back-up systems designed to capture and report data related to road, rail, aviation and marine movement, such as:
    <ul>
        <li>telematics (using technology to send, save and receive information between devices over a network, like the internet)</li>
        <li>geographic information systems (GIS)</li>
        <li>data systems</li>
        <li>traffic management communications</li>
        <li>back office systems</li>
    </ul>'
}),

(ansMTS:Answer {
    uuid: '00acc1b7-370f-4a45-9ce5-d57eba28b899',
    text: 'Major transport solutions',
    hint: 'For major transport solutions which will incorporate all of the transport services in one major project such as:
    <ul>
        <li>transport engineering and design services</li>
        <li>transport signage</li>
        <li>pedestrian management and control systems</li>
        <li>intelligent transport systems (such as, geographic, asset and environmental management and monitoring systems)</li>
        <li>environmental monitoring equipment and electric vehicle charging solutions)</li>
        <li>transport gate systems (hardware and software)</li>
    </ul>'
}),

(ansCatalogue:Answer {
    uuid: '6e7510cf-5ea4-4ae5-9c45-c069e035c3f6',
    text: 'Catalogue',
    hint: 'Buy low volume, low value goods and services by direct award, such as:
    <ul>
        <li>cameras including automated number plate recognition (ANPR), CCTV</li>
        <li>transport signage</li>
        <li>traffic lights</li>
        <li>street lighting</li>
        <li>electric vehicle (EV) chargers</li>
        <li>parking meters and systems</li>
        <li>pay and display systems</li>
    </ul>'
}),

(ansSustainable:Answer {
    uuid: '85d310ff-b9af-424d-a59c-3902f8e76675',
    text: 'Sustainable Transport Technologies',
    hint: 'Environmental monitoring systems, Fixed or Mobile sustainable transport infrastructure and intelligent transport systems (ITS), such as:
    <ul>
        <li>electric vehicle charging point equipment</li>
        <li>clean air zone technologies</li>
        <li>access and Payment solutions</li>
    </ul>'
}),

(ansVehicleCharging:Answer {
    uuid: '1216bdb4-70da-4456-a264-583f6a97358b',
    text: 'Vehicle charging infrastructure solutions',
    hint: 'This will help you buy charging infrastructure for electric and hybrid vehicles. Buy a full end to end service or specific elements of a service to meet your needs. Products and services available include:
    <ul>
        <li>installation of electric and hybrid chargers</li>
        <li>consultancy and feasibility services to help support your transition to low emission vehicles</li>
        <li>servicing and maintenance services for charging infrastructure</li>
        <li>associated hardware and accessories including charepoint equipment and peripherals (such as mounting poles and cables)</li>
    </ul>'
}),

(Agreement_RM6094:Agreement:Outcome {number: 'RM6094'})-[:HAS_LOT]->(:Lot {number: '1', url: '', type: 'CAT', scale: true}),
(Agreement_RM6213:Agreement:Outcome {number: 'RM6094'}),


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Tree Structure
(jrnyTransportTechService:Journey {uuid: '8699c0cc-230f-4f50-a11c-6c85d66ed69c', name: 'Transport Tech Service'}),
(jrnyTransportTechService)-[:FIRST_QUESTION]->(qiFirstQuestion:QuestionInstance:Outcome {uuid: 'e93aa7ec-df90-42f1-a89c-70078ed97adc'})-[:DEFINED_BY]->(qstnService),

(ansGrpEmerging:AnswerGroup {name: 'ansGrpEmerging'}),
(qiFirstQuestion)-[:HAS_ANSWER_GROUP]->(ansGrpEmerging),
(ansGrpEmerging)-[:HAS_ANSWER {order: 1}]->(ansEmerging),
(ansGrpEmerging)-[:HAS_OUTCOME]->(qiService1:QuestionInstance:Outcome {uuid: 'a605e36d-9191-4327-91e7-aa1ccdb21a4a'})-[:DEFINED_BY]->(qstnService),

    (ansGrpIoT:AnswerGroup {name: 'ansGrpIoT'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpIoT),
    (ansGrpIoT)-[:HAS_ANSWER {order: 1}]->(ansIoT),
    (ansGrpIoT)-[:HAS_OUTCOME]->(Agreement_RM6094),

    (ansGrpAI:AnswerGroup {name: 'ansGrpAI'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpAI),
    (ansGrpAI)-[:HAS_ANSWER {order: 2}]->(ansAI),
    (ansGrpAI)-[:HAS_OUTCOME]->(Agreement_RM6094),

    (ansGrpSimulated:AnswerGroup {name: 'ansGrpSimulated'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpSimulated),
    (ansGrpSimulated)-[:HAS_ANSWER {order: 3}]->(ansSimulated),
    (ansGrpSimulated)-[:HAS_OUTCOME]->(Agreement_RM6094),

    (ansGrpEngineering:AnswerGroup {name: 'ansGrpEngineering'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpEngineering),
    (ansGrpEngineering)-[:HAS_ANSWER {order: 4}]->(ansEngineering),
    (ansGrpEngineering)-[:HAS_OUTCOME]->(Agreement_RM6094),

    (ansGrpData:AnswerGroup {name: 'ansGrpData'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpData),
    (ansGrpData)-[:HAS_ANSWER {order: 5}]->(ansData),
    (ansGrpData)-[:HAS_OUTCOME]->(Agreement_RM6094),

    (ansGrpWearables:AnswerGroup {name: 'ansGrpWearables'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpWearables),
    (ansGrpWearables)-[:HAS_ANSWER {order: 6}]->(ansWearables),
    (ansGrpWearables)-[:HAS_OUTCOME]->(Agreement_RM6094),

    (ansGrpTransport2:AnswerGroup {name: 'ansGrpTransport2'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpTransport2),
    (ansGrpTransport2)-[:HAS_ANSWER {order: 7}]->(ansTransport2),
    (ansGrpTransport2)-[:HAS_OUTCOME]->(Agreement_RM6094),

    (ansGrpImplementation:AnswerGroup {name: 'ansGrpImplementation'}),
    (qiService1)-[:HAS_ANSWER_GROUP]->(ansGrpImplementation),
    (ansGrpImplementation)-[:HAS_ANSWER {order: 8}]->(ansImplementation),
    (ansGrpImplementation)-[:HAS_OUTCOME]->(Agreement_RM6094),

(ansGrpTransport:AnswerGroup {name: 'ansGrpTransport'}),
(qiFirstQuestion)-[:HAS_ANSWER_GROUP]->(ansGrpTransport),
(ansGrpTransport)-[:HAS_ANSWER {order: 2}]->(ansTransport),
(ansGrpTransport)-[:HAS_OUTCOME]->(qiService2:QuestionInstance:Outcome {uuid: '0137c861-e6eb-4dcd-8ff2-5cf80fc2781d'})-[:DEFINED_BY]->(qstnService),

    (ansGrpTPS:AnswerGroup {name: 'ansGrpTPS'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpTPS),
    (ansGrpTPS)-[:HAS_ANSWER {order: 1}]->(ansTPS),
    (ansGrpTPS)-[:HAS_OUTCOME]->(:Agreement:Outcome {number: 'RM6099'})-[:HAS_LOT]->(:Lot {number: '1', url: '', type: 'CAT', scale: true}),

    (ansGrpTPC:AnswerGroup {name: 'ansGrpTPC'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpTPC),
    (ansGrpTPC)-[:HAS_ANSWER {order: 2}]->(ansTPC),
    (ansGrpTPC)-[:HAS_OUTCOME]->(:Agreement:Outcome {number: 'RM6099'})-[:HAS_LOT]->(:Lot {number: '2', url: '', type: 'CAT', scale: true}),

    (ansGrpTSL:AnswerGroup {name: 'ansGrpTSL'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpTSL),
    (ansGrpTSL)-[:HAS_ANSWER {order: 3}]->(ansTSL),
    (ansGrpTSL)-[:HAS_OUTCOME]->(:Agreement:Outcome {number: 'RM6099'})-[:HAS_LOT]->(:Lot {number: '3', url: '', type: 'CAT', scale: true}),

    (ansGrpTDS:AnswerGroup {name: 'ansGrpTDS'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpTDS),
    (ansGrpTDS)-[:HAS_ANSWER {order: 4}]->(ansTDS),
    (ansGrpTDS)-[:HAS_OUTCOME]->(:Agreement:Outcome {number: 'RM6099'})-[:HAS_LOT]->(:Lot {number: '4', url: '', type: 'CAT', scale: true}),

    (ansGrpMTS:AnswerGroup {name: 'ansGrpMTS'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpMTS),
    (ansGrpMTS)-[:HAS_ANSWER {order: 5}]->(ansMTS),
    (ansGrpMTS)-[:HAS_OUTCOME]->(:Agreement:Outcome {number: 'RM6099'})-[:HAS_LOT]->(:Lot {number: '6', url: '', type: 'CAT', scale: true}),

    (ansGrpCatalogue:AnswerGroup {name: 'ansGrpCatalogue'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpCatalogue),
    (ansGrpCatalogue)-[:HAS_ANSWER {order: 6}]->(ansCatalogue),
    (ansGrpCatalogue)-[:HAS_OUTCOME]->(:Agreement:Outcome {number: 'RM6099'})-[:HAS_LOT]->(:Lot {number: '7', url: '', type: 'CAT', scale: true}),

    (ansGrpSustainable:AnswerGroup {name: 'ansGrpSustainable'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpSustainable),
    (ansGrpSustainable)-[:HAS_ANSWER {order: 7}]->(ansSustainable),
    (ansGrpSustainable)-[:HAS_OUTCOME]->(:Agreement:Outcome {number: 'RM6099'})-[:HAS_LOT]->(:Lot {number: '5', url: '', type: 'CAT', scale: true}),
    (ansGrpSustainable)-[:HAS_OUTCOME]->(Agreement_RM6213),

    (ansGrpVehicleCharging:AnswerGroup {name: 'ansGrpVehicleCharging'}),
    (qiService2)-[:HAS_ANSWER_GROUP]->(ansGrpVehicleCharging),
    (ansGrpVehicleCharging)-[:HAS_ANSWER {order: 8}]->(ansVehicleCharging),
    (ansGrpVehicleCharging)-[:HAS_OUTCOME]->(Agreement_RM6213);